name: 'Yarn'

description: 'Install the dependencies'

runs:
  using: 'composite'
  steps:
    # Note: Caller workflow is responsible for checkout. Don't checkout here as it would
    # override the ref that the caller already checked out (e.g., PR branch).
    - uses: ./.github/actions/corepack

    - name: Restore Yarn Cache & Types
      id: restore-yarn-types
      uses: ./.github/actions/cache-deps
      with:
        mode: restore-yarn

    - name: Echo cache hit
      shell: bash
      run: |
        echo "Yarn cache hit: ${{ steps.restore-yarn-types.outputs.cache-hit-yarn }}"

    - name: Yarn install
      if: steps.restore-yarn-types.outputs.cache-hit-yarn != 'true'
      shell: bash
      run: yarn install --immutable

    - name: Yarn after-install to generate contracts types
      if: steps.restore-yarn-types.outputs.cache-hit-yarn != 'true'
      shell: bash
      run: yarn workspace @safe-global/web after-install

    - name: Save Yarn Cache & Types
      if: steps.restore-yarn-types.outputs.cache-hit-yarn != 'true'
      uses: ./.github/actions/cache-deps
      with:
        mode: save-yarn
        key: ${{ steps.restore-yarn-types.outputs.computed-cache-key-yarn }}
