name: 'Yarn'

description: 'Set up Node.js and install dependencies'

inputs:
  after-install:
    description: 'Run web after-install step to generate contract types'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/corepack

    - uses: actions/setup-node@v6
      with:
        node-version: '24.14.0'
        cache: 'yarn'

    - name: Restore Yarn Cache & Types
      id: restore-yarn-types
      uses: ./.github/actions/cache-deps
      with:
        mode: restore-yarn

    - name: Echo cache hit
      shell: bash
      run: |
        echo "Yarn cache hit: ${{ steps.restore-yarn-types.outputs.cache-hit-yarn }}"

    - name: Yarn install
      if: steps.restore-yarn-types.outputs.cache-hit-yarn != 'true'
      shell: bash
      run: yarn install --immutable

    - name: Yarn after-install to generate contracts types
      if: steps.restore-yarn-types.outputs.cache-hit-yarn != 'true' && inputs.after-install == 'true'
      shell: bash
      run: yarn workspace @safe-global/web after-install

    - name: Save Yarn Cache & Types
      if: steps.restore-yarn-types.outputs.cache-hit-yarn != 'true'
      uses: ./.github/actions/cache-deps
      with:
        mode: save-yarn
        key: ${{ steps.restore-yarn-types.outputs.computed-cache-key-yarn }}
