compressionLevel: mixed

enableConstraintsChecks: true

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

packageExtensions:
  '@cowprotocol/widget-react@*':
    peerDependencies:
      '@types/react': ^19.1.0
      react: ^19.1.0
  '@storybook/core@*':
    dependencies:
      '@types/react': ^19.1.0
      react: ^19.1.0
  eslint-config-next@*:
    dependencies:
      next: '*'
  react-papaparse@*:
    peerDependencies:
      react: ^19.1.0
