services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-javascript:stable-1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

  cypress:
    image: cypress/base:latest
    depends_on:
      - app
    volumes:
      - .:/e2e
      - /dev/shm:/dev/shm
    working_dir: /e2e
    command: ["yarn", "cypress:open"]
