import type { EnemyDef, EnemyId } from './types'

/** Everyone who ever wanted to drain a Safe. HP values are for wave multiplier 1.0. */
export const ENEMIES: Record<EnemyId, EnemyDef> = {
  phisher: {
    id: 'phisher',
    name: 'Phishing bot',
    description: 'Mass-mailed "verify your wallet" links with legs. Weak alone, annoying in numbers.',
    hp: 45,
    speed: 1.6,
    armor: 'unarmored',
    armorValue: 0,
    bounty: 6,
    drain: 1,
    scale: 0.7,
    color: 0xff5f72,
  },
  dust: {
    id: 'dust',
    name: 'Dust particle',
    description: 'A fragment of an address poisoner. Tiny, quick, and worth almost nothing.',
    hp: 16,
    speed: 2.3,
    armor: 'unarmored',
    armorValue: 0,
    bounty: 2,
    drain: 1,
    scale: 0.42,
    color: 0xf79ba7,
  },
  poisoner: {
    id: 'poisoner',
    name: 'Address poisoner',
    description: 'Spams look-alike addresses into your history. Splits into dust when scanned.',
    hp: 95,
    speed: 1.3,
    armor: 'light',
    armorValue: 2,
    bounty: 10,
    drain: 1,
    scale: 0.85,
    color: 0xc86dd7,
    splitsInto: { enemy: 'dust', count: 3 },
  },
  drainer: {
    id: 'drainer',
    name: 'Drainer script',
    description: 'Sweeps approvals the moment a signature lands. Very fast and steals extra when it leaks.',
    hp: 60,
    speed: 2.6,
    armor: 'light',
    armorValue: 1,
    bounty: 9,
    drain: 2,
    scale: 0.65,
    color: 0xffb020,
  },
  blindSigner: {
    id: 'blindSigner',
    name: 'Blind signer',
    description: 'Signs whatever the hardware wallet shows. Slow, thick-skinned, and hard to stop.',
    hp: 330,
    speed: 0.8,
    armor: 'heavy',
    armorValue: 6,
    bounty: 21,
    drain: 2,
    scale: 1.15,
    color: 0x7d8a99,
  },
  lazarus: {
    id: 'lazarus',
    name: 'Lazarus operative',
    description: 'State-sponsored, well funded and patient. Heavy armor shrugs off basic scans.',
    hp: 210,
    speed: 1.2,
    armor: 'heavy',
    armorValue: 4,
    bounty: 18,
    drain: 2,
    scale: 0.95,
    color: 0xd93636,
  },
  socialEngineer: {
    id: 'socialEngineer',
    name: 'Social engineer',
    description: 'Looks exactly like a colleague on Slack. Invisible until a Tx Simulator reveals it.',
    hp: 125,
    speed: 1.4,
    armor: 'unarmored',
    armorValue: 0,
    bounty: 18,
    drain: 3,
    scale: 0.9,
    color: 0x9fe8ff,
    stealth: true,
  },
  delegatecall: {
    id: 'delegatecall',
    name: 'Malicious delegatecall',
    description: 'Flies straight over the path and rewrites your Safe from the inside. Air unit.',
    hp: 115,
    speed: 1.5,
    armor: 'light',
    armorValue: 1,
    bounty: 15,
    drain: 2,
    scale: 0.8,
    color: 0xff7ab8,
    flying: true,
  },
  mevBot: {
    id: 'mevBot',
    name: 'MEV bot',
    description: 'Front-runs everything, including your defenses. Fast air unit with little health.',
    hp: 70,
    speed: 3.0,
    armor: 'light',
    armorValue: 0,
    bounty: 12,
    drain: 1,
    scale: 0.6,
    color: 0x00e5ff,
    flying: true,
  },
  spoofedUi: {
    id: 'spoofedUi',
    name: 'Spoofed frontend',
    description: 'A pixel-perfect fake of the Safe{Wallet} UI. Its shield absorbs the first hits.',
    hp: 160,
    speed: 1.1,
    armor: 'light',
    armorValue: 3,
    bounty: 18,
    drain: 2,
    scale: 1.0,
    color: 0x3fd28a,
    shieldHits: 4,
  },
  approvalHijacker: {
    id: 'approvalHijacker',
    name: 'Approval hijacker',
    description: 'Lives off unlimited token approvals and regenerates while it walks.',
    hp: 270,
    speed: 1.3,
    armor: 'heavy',
    armorValue: 3,
    bounty: 22,
    drain: 3,
    scale: 1.0,
    color: 0xffd166,
    regen: 6,
  },
  rugWhale: {
    id: 'rugWhale',
    name: 'Rug pull whale',
    description: 'A compromised protocol treasury lumbering toward your Safe. Bursts into phishing bots when it falls.',
    hp: 3000,
    speed: 0.55,
    armor: 'fortified',
    armorValue: 7,
    bounty: 225,
    drain: 8,
    scale: 2.2,
    color: 0x2f6fed,
    splitsInto: { enemy: 'phisher', count: 8 },
    boss: true,
  },
  supplyWorm: {
    id: 'supplyWorm',
    name: 'Supply chain worm',
    description: 'A poisoned npm package crawling through your frontend. Regenerates and sheds drainers.',
    hp: 5600,
    speed: 0.75,
    armor: 'fortified',
    armorValue: 6,
    bounty: 450,
    drain: 10,
    scale: 2.0,
    color: 0x8bd346,
    regen: 28,
    splitsInto: { enemy: 'drainer', count: 5 },
    boss: true,
  },
  lazarusCommander: {
    id: 'lazarusCommander',
    name: 'Lazarus commander',
    description: 'The nation-state APT arrives in person. Regenerating shields and a steady stream of operatives.',
    hp: 11000,
    speed: 0.7,
    armor: 'fortified',
    armorValue: 9,
    bounty: 1500,
    drain: 20,
    scale: 2.4,
    color: 0x8a1c27,
    shieldHits: 6,
    shieldRegenSeconds: 8,
    summons: { enemy: 'lazarus', count: 2, everySeconds: 9 },
    boss: true,
  },
}
