name: 'Cache Next.js Build'
description: 'Restore or save the Next.js build cache'
inputs:
  mode:
    description: 'restore-nc | save-nc'
    required: true
  key:
    description: 'The cache key to use to save. Required when mode=save-nc; ignored on restore.'
    required: false

outputs:
  cache-hit-nc:
    value: ${{ steps.restore-nc.outputs.cache-hit }}
    description: 'Whether the cache was hit or not'
  computed-cache-key-nc:
    value: ${{ steps.restore-nc.outputs.cache-primary-key }}
    description: 'The computed cache key for nextjs/cypress'

runs:
  using: 'composite'
  steps:
    - name: Restore Next.js
      if: ${{ inputs.mode == 'restore-nc' }}
      id: restore-nc
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next/cache
        key: ${{ runner.os }}-nextjs-cypress-${{ hashFiles('apps/web/package.json', 'apps/web/yarn.lock') }}-${{ hashFiles('apps/web/src/**/*', 'apps/web/public/**/*', 'apps/web/*.{js,jsx,cjs,ts,mjs,tsx,json}') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-cypress-${{ hashFiles('apps/web/package.json', 'apps/web/yarn.lock') }}-

    - name: Save Next.js
      if: ${{ inputs.mode == 'save-nc' }}
      uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next/cache
        key: ${{inputs.key}}
