export const PROPOSER_ROLE_TITLE = 'Proposer role'
export const PROPOSER_ROLE_DESCRIPTION = 'Let teammates without signing rights propose transactions.'
export const CREATE_POLICY_TITLE = 'Create new policy'
export const PROPOSER_FIELD_HELPER =
  'The beneficiary that will have the ability to propose transactions, publicly visible'
export const PROPOSER_NAME_HELPER = 'Only you can see this name. Everyone else sees the address.'
export const GRANT_INFO_TITLE = 'You are about to grant the ability to propose transactions.'
export const GRANT_INFO_DESCRIPTION = 'To complete the setup, confirm with a signature from your connected wallet.'
export const PROPOSER_IS_SAFE_ERROR = 'Cannot add the Safe account itself as proposer'
export const PROPOSER_IS_OWNER_ERROR = 'Cannot add a signer of this Safe account as proposer'
export const PROPOSER_EXISTS_ERROR = 'This address is already a proposer of this Safe account'
export const PROPOSER_RESERVED_ERROR = 'This proposer address is not valid'
export const PROPOSER_SAFE_LOADING_MESSAGE = 'Loading the Safe account details, please wait'
export const PROPOSER_SAFE_ERROR_MESSAGE = 'Could not load the Safe account details, please try again'
