name: 'CLA Assistant'

on:
  pull_request:

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: Post a comment if the PR is from a fork
        if: ${{ github.event.pull_request.head.repo.full_name != 'safe-global/web-core' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: cla-comment
          message: |
            Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://safe.global/cla/) before we can accept your contribution. You can sign the CLA just by posting a comment as per the format below:

            ---

            I have read the CLA Document and I hereby sign the CLA

            ---

            Thank you! ✍️ ✅
