name: CLA

on:
  pull_request:

  pull_request_review_comment:

  issue_comment:

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA has been signed in this PR
        if: ${{ github.event.pull_request.head.repo.full_name != 'safe-global/web-core' }}
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: ${{ github.event.pull_request.user.login }}
          body-includes: 'I have read the CLA Document and I hereby sign the CLA'

      - name: Post a comment if the PR is from a fork
        if: ${{ github.event.pull_request.head.repo.full_name != 'safe-global/web-core' && steps.fc.outputs.comment-id == 0 }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: cla-comment
          message: |
            Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://safe.global/cla/) before we can accept your contribution. You can sign the CLA just by posting a comment as per the format below:

            ---

            *I have read the CLA Document and I hereby sign the CLA*

            ---

            Thank you!

      - name: Post a comment confirming the CLA was signed
        if: ${{ steps.fc.outputs.comment-id != 0 }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: cla-comment
          message: |
            All contributors have signed the CLA ✍️ ✅
