name: AI code review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    # Don't run on draft PRs
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          MODEL: gpt-4o # https://platform.openai.com/docs/models
          PROMPT: |
            Review the code changes in this PR and provide feedback if something is off.
            Skip politeness and get straight to the point.
            Only point out potential issues, don't comment on the good parts and the code that was already there prior to this PR.
            Pay attention to the logic, structure, and the usage of best practices and design patterns.
            Suggest refactoring if necessary. Keep it short if you aren't sure that the code is wrong.