name: Deploy to staging

on:
  workflow_run:
    workflows: ["Build"]
    branches: [staging]
    types: [completed]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    name: Deploy to staging
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Download the build artifact
        uses: actions/download-artifact@v3
        with:
          name: next-export-${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to the staging S3
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        # A hack to achieve blue-green deployments: run the sync command twice.
        # First time to upload new files, second time to upload the new files AND clean up old files.
        run: |
          aws s3 sync ./out s3://${{ secrets.STAGING_BUCKET_NAME }}/current
          aws s3 sync ./out s3://${{ secrets.STAGING_BUCKET_NAME }}/current --delete
