name: Regression tests

on:
  pull_request:
    branches:
      - 'release**'
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-20.04
    name: Cypress Regression tests
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3

      - uses: browser-actions/setup-chrome@v1

      - uses: ./.github/workflows/yarn

      - name: Install Cypress
        run: |
          ./node_modules/.bin/cypress install

      - uses: ./.github/workflows/build
        with:
          secrets: ${{ toJSON(secrets) }}
          e2e_mnemonic: ${{ secrets.NEXT_PUBLIC_CYPRESS_MNEMONIC }}

      - name: Serve
        run: yarn serve &

      - uses: cypress-io/github-action@v4
        with:
          parallel: true
          spec: cypress/e2e/**/*.cy.js
          browser: chrome
          record: true
          config: baseUrl=http://localhost:8080
          group: 'Regression tests'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
