name: Regression on demand tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1-5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-20.04
    name: Cypress Regression on demand tests
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/cypress
        with:
          secrets: ${{ toJSON(secrets) }}
          spec: cypress/e2e/**/*.cy.js
          group: 'Regression on demand tests'
