name: e2e

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Yarn install
        run: |
          rm -rf .yarncache
          yarn cache clean
          yarn install --frozen-lockfile

      - name: Build, serve & test
        run: |
          yarn build
          yarn export
          yarn serve &
          yarn cypress:run --config baseUrl=http://localhost:8080
        env:
          CYPRESS_MNEMONIC: ${{ secrets.CYPRESS_MNEMONIC }}
