name: e2e

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    needs: deploy
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # - uses: actions/checkout@v2

      # - uses: cypress-io/github-action@v2
      #   with:
      #     spec: cypress/integration/smoke/*.spec.js
      #     browser: chrome
      #     record: false
      #     config: baseUrl=https://${{ steps.extract_branch.outputs.branch }}.web-core.pages.dev
      #   env:
      #     CYPRESS_ENV: ${{ env.REACT_APP_ENV}}
      #     CYPRESS_MNEMONIC: ${{secrets.CYPRESS_MNEMONIC}}
