name: e2e

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: |
          mkdir .yarncache
          yarn install --cache-folder ./.yarncache --immutable
          rm -rf .yarncache
          yarn cache clean

      - name: Build & serve
        run: |
          yarn build
          yarn export
          yarn serve &

      - uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/smoke/*.cy.js
          browser: chrome
          record: false
          config: baseUrl=http://localhost:8080
        env:
          CYPRESS_ENV: ${{ env.REACT_APP_ENV}}
          CYPRESS_MNEMONIC: ${{secrets.CYPRESS_MNEMONIC}}
