name: e2e

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2

      - uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/smoke/*.cy.js
          browser: chrome
          record: false
          config: baseUrl=https://${{ github.head_ref || github.ref_name }}.web-core.pages.dev
        env:
          CYPRESS_ENV: ${{ env.REACT_APP_ENV}}
          CYPRESS_MNEMONIC: ${{secrets.CYPRESS_MNEMONIC}}
