name: Lint
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    permissions:
      checks: write
      pull-requests: read
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/yarn

      - uses: Maggi64/eslint-plus-action@master
        with:
          npmInstall: false
