name: 'Lint'
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Yarn cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: web-core-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: yarn install --immutable

      - uses: Maggi64/eslint-plus-action@master
        with:
          npmInstall: false
