name: Lint

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js w/ dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --verbose

      - name: Run ESLint
        uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          npmInstall: false

      - name: Ensure build works
        run: yarn build
