name: Mobile Lint

on:
  push:
    branches:
      - main
    paths:
      - apps/mobile/**
      - packages/**
  pull_request:
    paths:
      - apps/mobile/**
      - packages/**
      - .github/workflows/mobile-lint.yml

jobs:
  lint:
    permissions:
      checks: write
      contents: read
      pull-requests: read
      statuses: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: ./.github/actions/yarn
        with:
          after-install: 'false'

      # Run lint
      - name: Run lint
        run: |
          yarn workspace @safe-global/mobile run lint
