name: Package @safe-global/utils unit tests
on:
  pull_request:
    paths:
      - packages/utils/**
      - packages/store/**
  push:
    branches:
      - main
    paths:
      - packages/**
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    permissions:
      checks: write
      pull-requests: read
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/yarn

      - name: Annotations and coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        with:
          skip-step: install
          annotations: failed-tests
          package-manager: yarn
          test-script: yarn test
          working-directory: packages/utils
          github-token: ${{ secrets.GITHUB_TOKEN }}