name: e2e

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Build
        uses: ./.github/actions/build

      - name: Serve
        run: yarn serve &

      - uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/safe-apps/*.cy.js
          browser: chrome
          record: true
          config: baseUrl=http://localhost:8080
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SAFE_APPS_RECORD_KEY }}
          CYPRESS_MNEMONIC: ${{ secrets.NEXT_PUBLIC_CYPRESS_MNEMONIC }}
