# File: .github/workflows/storycheck-example.yml
name: StoryCheck Simple Web3 App

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Debug PATH
        run: |
          echo "Current PATH:"
          echo $PATH
      - uses: actions/checkout@v5
      - name: Check disk space (post-checkout)
        run: |
          echo "Disk usage after checkout:"
          df -h
      - uses: ./.github/actions/yarn
      - name: Check disk space (post-yarn)
        run: |
          echo "Disk usage after yarn install:"
          df -h
      # - name: Maximize disk space
      #   uses: easimon/maximize-build-space@v10
      #   with:
      #     remove-dotnet: 'true'  # Remove large .NET SDK if present
      #     overprovision-lvm: 'true'  # Expand root if possible
      - name: Run StoryCheck
        id: storycheck      
        uses: GuardianUI/storycheck@v0.1.4
        env: 
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}       
          HF_HOME: /mnt/hf_cache  # Redirect HF model downloads to /mnt (more space)
          NEXT_PUBLIC_MIXPANEL_TOKEN: ${{ secrets.NEXT_PUBLIC_MIXPANEL_TOKEN }} 
        with:
          storypath: 'user-stories/create-account'
          start-command: 'yarn workspace @safe-global/web start'
          wait-on: 'http://localhost:3000'
          wait-on-timeout: '60'
          app-working-directory: 'user-stories/create-account'
      - name: Check if passed
        if: ${{ steps.storycheck.outputs.passed != 'true' }}
        run: echo "StoryCheck failed!" && exit 1
      - name: Check disk space (final)
        if: always()
        run: |
          echo "Final disk usage:"
          df -h