# File: .github/workflows/storycheck-example.yml
name: StoryCheck Simple Web3 App

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/yarn

      - name: Run StoryCheck
        id: storycheck      
        uses: GuardianUI/storycheck@v0.1.4
        env: 
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}       
          NEXT_PUBLIC_MIXPANEL_TOKEN: ${{ secrets.NEXT_PUBLIC_MIXPANEL_TOKEN }} 

        with:
          storypath: 'user-stories/create-account'
          start-command: yarn workspace @safe-global/web start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: '60'
          app-working-directory: 'user-stories/create-account'
      - name: Check if passed
        if: ${{ steps.storycheck.outputs.passed != 'true' }}
        run: echo "StoryCheck failed!" && exit 1