# File: .github/workflows/storycheck-example.yml
name: StoryCheck Simple Web3 App

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check disk space (initial)
        run: |
          echo "Disk usage before any steps:"
          df -h
      - uses: actions/checkout@v5
      - name: Check disk space (post-checkout)
        run: |
          echo "Disk usage after checkout:"
          df -h
      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - uses: ./.github/actions/yarn
      - name: Check disk space (post-yarn)
        run: |
          echo "Disk usage after yarn install:"
          df -h
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('user-stories/create-account/requirements.txt') }}
          restore-keys: ${{ runner.os }}-playwright-
      - name: Cache Hugging Face model
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-hf-cache-${{ hashFiles('user-stories/create-account/requirements.txt') }}-${{ hashFiles('interpreter/ai/local_refexp.py') }}
          restore-keys: ${{ runner.os }}-hf-cache-
      - name: Check for port conflicts
        run: |
          echo "Checking if port 8545 is in use:"
          netstat -tuln | grep :8545 || echo "Port 8545 is free"
      - name: Verify Anvil installation
        run: |
          echo "Verifying Anvil installation:"
          anvil --version || { echo "Anvil not found or failed to run"; exit 1; }
      - name: Clean temporary files (pre-storycheck)
        run: |
          echo "Cleaning /tmp and pip cache before StoryCheck:"
          rm -rf /tmp/* ~/.cache/pip || true
          df -h
      - name: Run StoryCheck
        id: storycheck      
        uses: GuardianUI/storycheck@v0.1.4
        env: 
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}       
          NEXT_PUBLIC_MIXPANEL_TOKEN: ${{ secrets.NEXT_PUBLIC_MIXPANEL_TOKEN }} 
          STORYCHECK_DISABLE_VIDEOS: 'true'  # Disable video recordings to save disk
          STORYCHECK_ANVIL_LOG: 'true'  # Enable Anvil logging for debugging
        with:
          storypath: 'user-stories/create-account'
          start-command: 'yarn workspace @safe-global/web start'
          wait-on: 'http://localhost:3000'
          wait-on-timeout: '60'
          anvil-timeout: '60'  # Increase Anvil timeout to 60 seconds
          app-working-directory: 'user-stories/create-account'
      - name: Check if passed
        if: ${{ steps.storycheck.outputs.passed != 'true' }}
        run: echo "StoryCheck failed!" && exit 1
      - name: Clean temporary files (post-storycheck)
        if: always()
        run: |
          echo "Cleaning /tmp, pip cache, and results after StoryCheck:"
          rm -rf /tmp/* ~/.cache/pip results/* || true
          df -h
      - name: Check disk space (final)
        if: always()
        run: |
          echo "Final disk usage:"
          df -h