# File: .github/workflows/storycheck-example.yml
name: StoryCheck SAFE Create Account Example

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  check:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'e2e-test')
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Check disk space (post-checkout)
        run: |
          echo "Disk usage after checkout:"
          df -h
      - name: Run StoryCheck
        id: storycheck      
        uses: GuardianUI/storycheck@v0.1.4
        env: 
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}       
        with:
          storypath: 'user-stories/create-account'
      - name: Check if passed
        if: ${{ steps.storycheck.outputs.passed != 'true' }}
        run: echo "StoryCheck failed!" && exit 1
