name: Unit tests
on:
  pull_request:

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Yarn cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: web-core-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: yarn install --immutable

      - name: Run tests
        run: 'yarn test:ci'

      - name: Comment in failing tests
        uses: mattallty/jest-github-action@v1.0.3
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'echo unit tests already executed'
          coverage-comment: false
