name: Unit tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Jest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
      - uses: actions/checkout@v3

      - name: Setup Node.js w/ yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Jest tests
        run: 'yarn test:ci'

      - name: Add failing tests comment
        uses: mattallty/jest-github-action@v1.0.3
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'echo unit tests already executed'
          coverage-comment: false
