name: Unit tests
on:
  pull_request:

  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/yarn

      - name: Run tests
        run: 'yarn test:ci'

      - name: Annotations and coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: jest.results.json
          test-script: 'echo coverage generated'
