name: Visual Regression Tests

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lost Pixel

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/yarn

      - name: Build app
        run: yarn workspace @safe-global/web build
        env:
          NEXT_PUBLIC_IS_OFFICIAL_HOST: true

      - name: Start server (in background)
        run: npx next start -p 3000 &
        working-directory: apps/web

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.16.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
