name: Web Type Check
on:
  pull_request:
    paths:
      - apps/web/**
      - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    permissions:
      checks: write
      pull-requests: read
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/yarn

      - name: Type check
        run: yarn type-check
        working-directory: apps/web

