name: Web Prettier
permissions:
  contents: read

on:
  pull_request:
    paths:
      - apps/web/**
      - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    permissions:
      checks: write
      pull-requests: read
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/yarn

      - name: Run Prettier check
        run: yarn workspace @safe-global/web prettier
