# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: 'Web Next.js Bundle Analysis'

on:
  pull_request:
    paths:
      - apps/web/**
  push:
    branches:
      - dev
    paths:
      - apps/web/**
      - packages/**
permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies
        uses: ./.github/actions/yarn

      - name: Build next.js app
        uses: ./.github/actions/build
        with:
          secrets: |-
            {
              "NEXT_PUBLIC_BEAMER_ID": ${{ toJSON(secrets.NEXT_PUBLIC_BEAMER_ID) }},
              "NEXT_PUBLIC_BLOCKAID_CLIENT_ID": ${{ toJSON(secrets.NEXT_PUBLIC_BLOCKAID_CLIENT_ID) }},
              "NEXT_PUBLIC_BRAND_LOGO": ${{ toJSON(secrets.NEXT_PUBLIC_BRAND_LOGO) }},
              "NEXT_PUBLIC_BRAND_NAME": ${{ toJSON(secrets.NEXT_PUBLIC_BRAND_NAME) }},
              "NEXT_PUBLIC_CONFIG_SERVICE_KEY": ${{ toJSON(secrets.NEXT_PUBLIC_CONFIG_SERVICE_KEY) }},
              "NEXT_PUBLIC_DATADOG_RUM_APPLICATION_ID": ${{ toJSON(secrets.NEXT_PUBLIC_DATADOG_RUM_APPLICATION_ID) }},
              "NEXT_PUBLIC_DATADOG_RUM_CLIENT_TOKEN": ${{ toJSON(secrets.NEXT_PUBLIC_DATADOG_RUM_CLIENT_TOKEN) }},
              "NEXT_PUBLIC_DATADOG_RUM_ENV": ${{ toJSON(secrets.NEXT_PUBLIC_DATADOG_RUM_ENV) }},
              "NEXT_PUBLIC_DATADOG_RUM_SERVICE": ${{ toJSON(secrets.NEXT_PUBLIC_DATADOG_RUM_SERVICE) }},
              "NEXT_PUBLIC_DATADOG_RUM_SESSION_REPLAY_SAMPLE_RATE": ${{ toJSON(secrets.NEXT_PUBLIC_DATADOG_RUM_SESSION_REPLAY_SAMPLE_RATE) }},
              "NEXT_PUBLIC_DATADOG_RUM_SESSION_SAMPLE_RATE": ${{ toJSON(secrets.NEXT_PUBLIC_DATADOG_RUM_SESSION_SAMPLE_RATE) }},
              "NEXT_PUBLIC_DATADOG_RUM_SITE": ${{ toJSON(secrets.NEXT_PUBLIC_DATADOG_RUM_SITE) }},
              "NEXT_PUBLIC_DATADOG_RUM_TRACE_SAMPLE_RATE": ${{ toJSON(secrets.NEXT_PUBLIC_DATADOG_RUM_TRACE_SAMPLE_RATE) }},
              "NEXT_PUBLIC_DATADOG_RUM_TRACING_ENABLED": ${{ toJSON(secrets.NEXT_PUBLIC_DATADOG_RUM_TRACING_ENABLED) }},
              "NEXT_PUBLIC_ECOSYSTEM_ID_ADDRESS": ${{ toJSON(secrets.NEXT_PUBLIC_ECOSYSTEM_ID_ADDRESS) }},
              "NEXT_PUBLIC_FIREBASE_OPTIONS_PRODUCTION": ${{ toJSON(secrets.NEXT_PUBLIC_FIREBASE_OPTIONS_PRODUCTION) }},
              "NEXT_PUBLIC_FIREBASE_OPTIONS_STAGING": ${{ toJSON(secrets.NEXT_PUBLIC_FIREBASE_OPTIONS_STAGING) }},
              "NEXT_PUBLIC_FIREBASE_VAPID_KEY_PRODUCTION": ${{ toJSON(secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY_PRODUCTION) }},
              "NEXT_PUBLIC_FIREBASE_VAPID_KEY_STAGING": ${{ toJSON(secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY_STAGING) }},
              "NEXT_PUBLIC_GATEWAY_URL_PRODUCTION": ${{ toJSON(secrets.NEXT_PUBLIC_GATEWAY_URL_PRODUCTION) }},
              "NEXT_PUBLIC_GATEWAY_URL_STAGING": ${{ toJSON(secrets.NEXT_PUBLIC_GATEWAY_URL_STAGING) }},
              "NEXT_PUBLIC_INFURA_TOKEN": ${{ toJSON(secrets.NEXT_PUBLIC_INFURA_TOKEN) }},
              "NEXT_PUBLIC_INFURA_TOKEN_DEVSTAGING": ${{ toJSON(secrets.NEXT_PUBLIC_INFURA_TOKEN_DEVSTAGING) }},
              "NEXT_PUBLIC_IS_BEHIND_IAP": ${{ toJSON(secrets.NEXT_PUBLIC_IS_BEHIND_IAP) }},
              "NEXT_PUBLIC_IS_OFFICIAL_HOST": ${{ toJSON(secrets.NEXT_PUBLIC_IS_OFFICIAL_HOST) }},
              "NEXT_PUBLIC_PROD_GA_TRACKING_ID": ${{ toJSON(secrets.NEXT_PUBLIC_PROD_GA_TRACKING_ID) }},
              "NEXT_PUBLIC_PROD_HYPERNATIVE_OUTREACH_ID": ${{ toJSON(secrets.NEXT_PUBLIC_PROD_HYPERNATIVE_OUTREACH_ID) }},
              "NEXT_PUBLIC_PROD_MIXPANEL_TOKEN": ${{ toJSON(secrets.NEXT_PUBLIC_PROD_MIXPANEL_TOKEN) }},
              "NEXT_PUBLIC_PYLON_APP_ID": ${{ toJSON(secrets.NEXT_PUBLIC_PYLON_APP_ID) }},
              "NEXT_PUBLIC_PYLON_CHAT_URL": ${{ toJSON(secrets.NEXT_PUBLIC_PYLON_CHAT_URL) }},
              "NEXT_PUBLIC_SAFENET_CHAIN_ID": ${{ toJSON(secrets.NEXT_PUBLIC_SAFENET_CHAIN_ID) }},
              "NEXT_PUBLIC_SAFENET_CONSENSUS_ADDRESS": ${{ toJSON(secrets.NEXT_PUBLIC_SAFENET_CONSENSUS_ADDRESS) }},
              "NEXT_PUBLIC_SAFENET_COORDINATOR_ADDRESS": ${{ toJSON(secrets.NEXT_PUBLIC_SAFENET_COORDINATOR_ADDRESS) }},
              "NEXT_PUBLIC_SAFENET_ORACLE_ADDRESSES": ${{ toJSON(secrets.NEXT_PUBLIC_SAFENET_ORACLE_ADDRESSES) }},
              "NEXT_PUBLIC_SAFENET_RPC_URLS": ${{ toJSON(secrets.NEXT_PUBLIC_SAFENET_RPC_URLS) }},
              "NEXT_PUBLIC_SAFE_APPS_GA_TRACKING_ID": ${{ toJSON(secrets.NEXT_PUBLIC_SAFE_APPS_GA_TRACKING_ID) }},
              "NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN": ${{ toJSON(secrets.NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN) }},
              "NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN_DEVSTAGING": ${{ toJSON(secrets.NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN_DEVSTAGING) }},
              "NEXT_PUBLIC_SAFE_STATUS_PAGE_URL": ${{ toJSON(secrets.NEXT_PUBLIC_SAFE_STATUS_PAGE_URL) }},
              "NEXT_PUBLIC_SAFE_VERSION": ${{ toJSON(secrets.NEXT_PUBLIC_SAFE_VERSION) }},
              "NEXT_PUBLIC_STAGING_HYPERNATIVE_OUTREACH_ID": ${{ toJSON(secrets.NEXT_PUBLIC_STAGING_HYPERNATIVE_OUTREACH_ID) }},
              "NEXT_PUBLIC_STAGING_MIXPANEL_TOKEN": ${{ toJSON(secrets.NEXT_PUBLIC_STAGING_MIXPANEL_TOKEN) }},
              "NEXT_PUBLIC_SUPPORT_CHAT_ALIAS_DOMAIN": ${{ toJSON(secrets.NEXT_PUBLIC_SUPPORT_CHAT_ALIAS_DOMAIN) }},
              "NEXT_PUBLIC_SUPPORT_CHAT_ALLOWED_PARENTS": ${{ toJSON(secrets.NEXT_PUBLIC_SUPPORT_CHAT_ALLOWED_PARENTS) }},
              "NEXT_PUBLIC_TENDERLY_ORG_NAME": ${{ toJSON(secrets.NEXT_PUBLIC_TENDERLY_ORG_NAME) }},
              "NEXT_PUBLIC_TENDERLY_PROJECT_NAME": ${{ toJSON(secrets.NEXT_PUBLIC_TENDERLY_PROJECT_NAME) }},
              "NEXT_PUBLIC_TENDERLY_SIMULATE_ENDPOINT_URL": ${{ toJSON(secrets.NEXT_PUBLIC_TENDERLY_SIMULATE_ENDPOINT_URL) }},
              "NEXT_PUBLIC_TEST_GA_TRACKING_ID": ${{ toJSON(secrets.NEXT_PUBLIC_TEST_GA_TRACKING_ID) }},
              "NEXT_PUBLIC_TURNSTILE_SITE_KEY_PRODUCTION": ${{ toJSON(secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY_PRODUCTION) }},
              "NEXT_PUBLIC_TURNSTILE_SITE_KEY_STAGING": ${{ toJSON(secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY_STAGING) }},
              "NEXT_PUBLIC_WC_PROJECT_ID": ${{ toJSON(secrets.NEXT_PUBLIC_WC_PROJECT_ID) }},
              "NEXT_PUBLIC_ZODIAC_SECURITY_CHECK_URL": ${{ toJSON(secrets.NEXT_PUBLIC_ZODIAC_SECURITY_CHECK_URL) }}
            }

      - name: Analyze bundle
        run: |
          cd apps/web
          npx -p nextjs-bundle-analysis@0.5.0 report

      - name: Upload bundle
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bundle
          path: apps/web/.next/analyze/__bundle_analysis.json

      - name: List artifacts from default branch
        id: list_artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          runs=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/workflows/web-nextjs-bundle-analysis.yml/runs?event=push&branch=dev&status=success&per_page=1")

          artifacts_url=$(echo "$runs" | jq -r '.workflow_runs[0].artifacts_url')
          artifacts=$(curl -s -H "Authorization: Bearer $GH_TOKEN" "$artifacts_url")

          artifact_id=$(echo "$artifacts" | jq -r '.artifacts[] | select(.name=="bundle" and .expired==false) | .id')

          echo "artifact_id=$artifact_id" >> $GITHUB_OUTPUT

      - name: Download artifact zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ARTIFACT_ID: ${{ steps.list_artifacts.outputs.artifact_id }}
        run: |
          curl -L \
            -H "Authorization: Bearer $GH_TOKEN" \
            -o artifact.zip \
            "https://api.github.com/repos/$REPO/actions/artifacts/$ARTIFACT_ID/zip"

      - name: Unzip artifact
        run: unzip artifact.zip -d apps/web/.next/analyze/base && mkdir -p apps/web/.next/analyze/base/bundle && mv apps/web/.next/analyze/base/__bundle_analysis.json apps/web/.next/analyze/base/bundle/

      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: |
          cd apps/web
          ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis@0.5.0 compare

      - name: Get Comment Body
        id: get-comment-body
        if: success() && github.event.number
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        run: |
          cd apps/web
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat .next/analyze/__bundle_analysis_comment.txt)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Comment
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        with:
          header: next-bundle-analysis
          message: ${{ steps.get-comment-body.outputs.body }}
