name: Web Happy path on demand tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 3'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Cypress Happy path on demand tests
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/cypress
        env:
          BEAMER_DATA_E2E: ${{ secrets.BEAMER_DATA_E2E }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_WALLET_CREDENTIALS: ${{ secrets.CYPRESS_WALLET_CREDENTIALS }}
          NEXT_PUBLIC_BEAMER_ID: ${{ secrets.NEXT_PUBLIC_BEAMER_ID }}
          NEXT_PUBLIC_BLOCKAID_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_BLOCKAID_CLIENT_ID }}
          NEXT_PUBLIC_BRAND_LOGO: ${{ secrets.NEXT_PUBLIC_BRAND_LOGO }}
          NEXT_PUBLIC_BRAND_NAME: ${{ secrets.NEXT_PUBLIC_BRAND_NAME }}
          NEXT_PUBLIC_CONFIG_SERVICE_KEY: ${{ secrets.NEXT_PUBLIC_CONFIG_SERVICE_KEY }}
          NEXT_PUBLIC_DATADOG_RUM_APPLICATION_ID: ${{ secrets.NEXT_PUBLIC_DATADOG_RUM_APPLICATION_ID }}
          NEXT_PUBLIC_DATADOG_RUM_CLIENT_TOKEN: ${{ secrets.NEXT_PUBLIC_DATADOG_RUM_CLIENT_TOKEN }}
          NEXT_PUBLIC_DATADOG_RUM_ENV: ${{ secrets.NEXT_PUBLIC_DATADOG_RUM_ENV }}
          NEXT_PUBLIC_DATADOG_RUM_SERVICE: ${{ secrets.NEXT_PUBLIC_DATADOG_RUM_SERVICE }}
          NEXT_PUBLIC_DATADOG_RUM_SESSION_REPLAY_SAMPLE_RATE: ${{ secrets.NEXT_PUBLIC_DATADOG_RUM_SESSION_REPLAY_SAMPLE_RATE }}
          NEXT_PUBLIC_DATADOG_RUM_SESSION_SAMPLE_RATE: ${{ secrets.NEXT_PUBLIC_DATADOG_RUM_SESSION_SAMPLE_RATE }}
          NEXT_PUBLIC_DATADOG_RUM_SITE: ${{ secrets.NEXT_PUBLIC_DATADOG_RUM_SITE }}
          NEXT_PUBLIC_DATADOG_RUM_TRACE_SAMPLE_RATE: ${{ secrets.NEXT_PUBLIC_DATADOG_RUM_TRACE_SAMPLE_RATE }}
          NEXT_PUBLIC_DATADOG_RUM_TRACING_ENABLED: ${{ secrets.NEXT_PUBLIC_DATADOG_RUM_TRACING_ENABLED }}
          NEXT_PUBLIC_ECOSYSTEM_ID_ADDRESS: ${{ secrets.NEXT_PUBLIC_ECOSYSTEM_ID_ADDRESS }}
          NEXT_PUBLIC_FIREBASE_OPTIONS_PRODUCTION: ${{ secrets.NEXT_PUBLIC_FIREBASE_OPTIONS_PRODUCTION }}
          NEXT_PUBLIC_FIREBASE_OPTIONS_STAGING: ${{ secrets.NEXT_PUBLIC_FIREBASE_OPTIONS_STAGING }}
          NEXT_PUBLIC_FIREBASE_VAPID_KEY_PRODUCTION: ${{ secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY_PRODUCTION }}
          NEXT_PUBLIC_FIREBASE_VAPID_KEY_STAGING: ${{ secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY_STAGING }}
          NEXT_PUBLIC_GATEWAY_URL_PRODUCTION: ${{ secrets.NEXT_PUBLIC_GATEWAY_URL_PRODUCTION }}
          NEXT_PUBLIC_GATEWAY_URL_STAGING: ${{ secrets.NEXT_PUBLIC_GATEWAY_URL_STAGING }}
          NEXT_PUBLIC_INFURA_TOKEN: ${{ secrets.NEXT_PUBLIC_INFURA_TOKEN }}
          NEXT_PUBLIC_INFURA_TOKEN_DEVSTAGING: ${{ secrets.NEXT_PUBLIC_INFURA_TOKEN_DEVSTAGING }}
          NEXT_PUBLIC_IS_BEHIND_IAP: ${{ secrets.NEXT_PUBLIC_IS_BEHIND_IAP }}
          NEXT_PUBLIC_IS_OFFICIAL_HOST: ${{ secrets.NEXT_PUBLIC_IS_OFFICIAL_HOST }}
          NEXT_PUBLIC_PROD_GA_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_PROD_GA_TRACKING_ID }}
          NEXT_PUBLIC_PROD_HYPERNATIVE_OUTREACH_ID: ${{ secrets.NEXT_PUBLIC_PROD_HYPERNATIVE_OUTREACH_ID }}
          NEXT_PUBLIC_PROD_MIXPANEL_TOKEN: ${{ secrets.NEXT_PUBLIC_PROD_MIXPANEL_TOKEN }}
          NEXT_PUBLIC_PYLON_APP_ID: ${{ secrets.NEXT_PUBLIC_PYLON_APP_ID }}
          NEXT_PUBLIC_PYLON_CHAT_URL: ${{ secrets.NEXT_PUBLIC_PYLON_CHAT_URL }}
          NEXT_PUBLIC_SAFENET_CHAIN_ID: ${{ secrets.NEXT_PUBLIC_SAFENET_CHAIN_ID }}
          NEXT_PUBLIC_SAFENET_CONSENSUS_ADDRESS: ${{ secrets.NEXT_PUBLIC_SAFENET_CONSENSUS_ADDRESS }}
          NEXT_PUBLIC_SAFENET_COORDINATOR_ADDRESS: ${{ secrets.NEXT_PUBLIC_SAFENET_COORDINATOR_ADDRESS }}
          NEXT_PUBLIC_SAFENET_ORACLE_ADDRESSES: ${{ secrets.NEXT_PUBLIC_SAFENET_ORACLE_ADDRESSES }}
          NEXT_PUBLIC_SAFENET_RPC_URLS: ${{ secrets.NEXT_PUBLIC_SAFENET_RPC_URLS }}
          NEXT_PUBLIC_SAFE_APPS_GA_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_SAFE_APPS_GA_TRACKING_ID }}
          NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN: ${{ secrets.NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN }}
          NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN_DEVSTAGING: ${{ secrets.NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN_DEVSTAGING }}
          NEXT_PUBLIC_SAFE_STATUS_PAGE_URL: ${{ secrets.NEXT_PUBLIC_SAFE_STATUS_PAGE_URL }}
          NEXT_PUBLIC_SAFE_VERSION: ${{ secrets.NEXT_PUBLIC_SAFE_VERSION }}
          NEXT_PUBLIC_STAGING_HYPERNATIVE_OUTREACH_ID: ${{ secrets.NEXT_PUBLIC_STAGING_HYPERNATIVE_OUTREACH_ID }}
          NEXT_PUBLIC_STAGING_MIXPANEL_TOKEN: ${{ secrets.NEXT_PUBLIC_STAGING_MIXPANEL_TOKEN }}
          NEXT_PUBLIC_SUPPORT_CHAT_ALIAS_DOMAIN: ${{ secrets.NEXT_PUBLIC_SUPPORT_CHAT_ALIAS_DOMAIN }}
          NEXT_PUBLIC_SUPPORT_CHAT_ALLOWED_PARENTS: ${{ secrets.NEXT_PUBLIC_SUPPORT_CHAT_ALLOWED_PARENTS }}
          NEXT_PUBLIC_TENDERLY_ORG_NAME: ${{ secrets.NEXT_PUBLIC_TENDERLY_ORG_NAME }}
          NEXT_PUBLIC_TENDERLY_PROJECT_NAME: ${{ secrets.NEXT_PUBLIC_TENDERLY_PROJECT_NAME }}
          NEXT_PUBLIC_TENDERLY_SIMULATE_ENDPOINT_URL: ${{ secrets.NEXT_PUBLIC_TENDERLY_SIMULATE_ENDPOINT_URL }}
          NEXT_PUBLIC_TEST_GA_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_TEST_GA_TRACKING_ID }}
          NEXT_PUBLIC_TURNSTILE_SITE_KEY_PRODUCTION: ${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY_PRODUCTION }}
          NEXT_PUBLIC_TURNSTILE_SITE_KEY_STAGING: ${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY_STAGING }}
          NEXT_PUBLIC_WC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WC_PROJECT_ID }}
          NEXT_PUBLIC_ZODIAC_SECURITY_CHECK_URL: ${{ secrets.NEXT_PUBLIC_ZODIAC_SECURITY_CHECK_URL }}
        with:
          spec: |
            cypress/e2e/happypath/*.cy.js
          group: 'Happy path on demand tests'
          tag: 'happypath'

      - name: Python setup
        if: always()
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'

      - name: Install junitparser
        if: always()
        run: |
          pip install 'junitparser==5.0.1'

      - name: Merge JUnit reports for TestRail
        if: always()
        run: |
          junitparser merge --suite-name "Root Suite" --glob "apps/web/reports/junit-*" "apps/web/reports/junit-report.xml"

      - name: TestRail CLI upload results
        if: always()
        env:
          TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
          TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
          TESTRAIL_RUN_DESCRIPTION: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          pip install 'trcli==1.15.2'
          trcli -y \
          -h https://gno.testrail.io/ \
          --project "Safe- Web App" \
          --username "$TESTRAIL_USERNAME" \
          --password "$TESTRAIL_PASSWORD" \
          parse_junit \
          --title "Happy Path Automated Tests, branch: ${GITHUB_REF_NAME}" \
          --run-description "$TESTRAIL_RUN_DESCRIPTION" \
          -f "apps/web/reports/junit-report.xml"
