name: Web Smoke tests

on:
  workflow_run:
    workflows: ['Web Build']
    types: [completed]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Cypress Smoke tests

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]

    steps:
      - uses: actions/checkout@v5

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: apps/web
          run-id: ${{ github.event.workflow_run.id }}

      - uses: ./.github/actions/cypress
        with:
          secrets: ${{ toJSON(secrets) }}
          spec: cypress/e2e/smoke/*.cy.js
          group: 'Smoke tests'
          tag: 'smoke'
          skip-build: true
